#logging.level.org.springframework=info
#management.endpoints.web.exposure.include=*
##spring.datasource.url=jdbc:h2:mem:testdb
#spring.jpa.defer-datasource-initialization=true
#spring.jpa.show-sql=true
#spring.datasource.url=jdbc:mysql://localhost:3306/social-media-database
#spring.datasource.username=social-media-user
#spring.datasource.password=dummypassword
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.security.user.name=username
#spring.security.user.password=password
logging:
  level:
    org:
      springframework: info
management:
  endpoints:
    web:
      exposure:
        include: '*'
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/social-media-database
    username: social-media-user
    password: dummypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: username
      password: password
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
aws:
  region: ap-east-1
  s3:
    bucket:
      name: musing-test