--insert into user_details (id, birth_date, name)
--values (10001, current_date(), 'Ranga');
--
--insert into user_details (id, birth_date, name)
--values (10002, current_date(), 'Yasuo');
--
--insert into user_details (id, birth_date, name)
--values (10003, current_date(), 'Riven');
--
--insert into user_details (id, birth_date, name)
--values (10004, current_date(), 'Katarina');
--
--insert into post(id, description, user_id)
--values (20001, 'I want to learn AWS', 10002);
--
--insert into post(id, description, user_id)
--values (20002, 'I want to learn DevOps', 10003);
--
--insert into post(id, description, user_id)
--values (20003, 'I want to learn Spring boot', 10003);